#############################
# CartoDB Production Instance
#############################
production:
  host: 'https://api.cartodb.com'
  oauth_key: 'qOySvJB5RAE7rV2HfEXHFlvDINk6qxoP4zV6XxZI'
  oauth_secret: 'O2FdYgZQo2bcGyf2uUit0MlZvS8x07oSrScTjbUs'
  table_name: 'crisis'

#  auth_key: 'NJjm30LDCThhHteEuL8Zf1I2DhJ6qJHvIgpwAH91'
#  oauth_secret: 'zw3wb51WSONT4yUAY8KFcPbboISPavY7l6BwMDaO'
#  table_name: 'zonas_reparto'
#  cache_timeout: 60
#  debug: true
#  ssl_peer_verification: true

#############################
# CartoDB Local Instance
#############################
development:
  host: 'https://api.cartodb.com'
  oauth_key: 'qOySvJB5RAE7rV2HfEXHFlvDINk6qxoP4zV6XxZI'
  oauth_secret: 'O2FdYgZQo2bcGyf2uUit0MlZvS8x07oSrScTjbUs'
  table_name: 'crisis'
