#############################
# CartoDB Production Instance
#############################
production:
  host: 'https://api.cartodb.com'
  oauth_key: 'z5aou4GfIVqh9KLBbgKW2gUcj6X0yRZ1TpJgLw6I'
  oauth_secret: 'F7P0uYeUKsEPahdTY1NizUclLqsR5mijaoWU1Vkm'
  table_name: 'crisis'

#  auth_key: 'NJjm30LDCThhHteEuL8Zf1I2DhJ6qJHvIgpwAH91'
#  oauth_secret: 'zw3wb51WSONT4yUAY8KFcPbboISPavY7l6BwMDaO'
#  table_name: 'zonas_reparto'
#  cache_timeout: 60
  debug: true
  ssl_peer_verification: true

#############################
# CartoDB Local Instance
#############################
development:
  host: 'https://api.cartodb.com'
  oauth_key: 'z5aou4GfIVqh9KLBbgKW2gUcj6X0yRZ1TpJgLw6I'
  oauth_secret: 'F7P0uYeUKsEPahdTY1NizUclLqsR5mijaoWU1Vkm'
  table_name: 'crisis'
